<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Album ID' => 'Álbum ID',
    'Albumes' => 'Álbumes',
    'Anyo' => 'Año de creación',
    'Are you sure you want to delete this item?' => '¿Estás seguro de que desea eliminar este elemento?',
    'Confirm Token' => 'Token de confirmación',
    'Create Albumes' => 'Añadir un álbum',
    'Create Canciones' => 'Añadir una canción',
    'Create Generos' => 'Añadir un género',
    'Created At' => 'Creado en',
    'Delete' => 'Eliminar',
    'Denominacion' => 'Denominación',
    'Duracion' => 'Duración',
    'Fnac' => 'Fecha de nac.',
    'Genero ID' => 'Género ID',
    'Generos' => 'Géneros',
    'Password' => 'Contraseña',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'The requested page does not exist.' => 'La páginas solicitada no existe',
    'Titulo' => 'Título',
    'Update' => 'Actualizar',
    'Update Albumes: {name}' => 'Actualiza el álbum: {name}',
    'Update Canciones: {name}' => 'Actualizar la canción: {name}',
    'Update Generos: {name}' => 'Actualizar el género: {name}',
    'Url Cancion' => 'Url canción',
    'Url Portada' => 'Url portada',
    'Apellidos' => '',
    'Auth Key' => '',
    'Canciones' => '',
    'Create Usuarios' => 'Añadir un usuario',
    'Email' => '',
    'Género' => '',
    'ID' => '',
    'Login' => '',
    'Nombre' => '',
    'Reset' => '',
    'Rol' => '',
    'Título del álbum' => '',
    'Update Usuarios: {name}' => 'Actualizar el usuario: {name}',
    'Usuario ID' => '',
    'Usuarios' => '',
    'Remember me' => 'Recuérdame',
    'Password Repeat' => 'Repetir contraseña',
    'Introduzca los siguientes datos para registrarse:' => '',
    'Registrar un usuario' => '',
];
