<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Albumes' => 'Albums',
    'Anyo' => 'Year',
    'Apellidos' => 'Surnames',
    'Canciones' => 'Songs',
    'Create Albumes' => 'Add an album',
    'Create Canciones' => 'Add a song',
    'Create Generos' => 'Add a genre',
    'Create Usuarios' => 'Add an user',
    'Denominacion' => 'Denomination',
    'Duracion' => 'Duration',
    'Entrar' => 'Sign in',
    'Fnac' => 'Date of birth',
    'Genero ID' => 'Genre ID',
    'Generos' => 'Genres',
    'Género' => 'Genre',
    'Inicia sesión con tu nombre de usuario' => 'Sign in with your username',
    'Nombre' => 'Name',
    'Nombre de usuario' => 'Username',
    'Registrarse' => 'Sign up',
    'Regístrate con tu dirección de correo electrónico' => 'Sign up with your email',
    'Titulo' => 'Title',
    'Título del álbum' => 'Album title',
    'Update Albumes: {name}' => 'Update album: {name}',
    'Update Canciones: {name}' => 'Update song: {name}',
    'Update Generos: {name}' => 'Update genre: {name}',
    'Update Usuarios: {name}' => 'Update user: {name}',
    'Url Cancion' => 'Song url',
    'Url Portada' => 'Cover url',
    'Usuario ID' => 'User ID',
    'Usuarios' => 'Users',
    'Album ID' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Confirm Token' => '',
    'Created At' => '',
    'Delete' => '',
    'Email' => '',
    'ID' => '',
    'Login' => '',
    'Password' => '',
    'Reset' => '',
    'Rol' => 'Role',
    'Save' => '',
    'Search' => '',
    'Siguiente' => 'Next',
    'Anterior' => 'Previous',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Introduzca los siguientes datos para registrarse:' => '@@Enter the following information to register:@@',
    'Password Repeat' => 'Repeat password',
    'Registrar un usuario' => '@@Register an user@@',
    'Remember me' => '',
    'My account' => '',
    'Logout' => '',
    'Actions' => '',
    'Posts' => '',
    'Followers' => '',
    'Following' => '',
    'ConfirmMail' => 'An email has been sent to your email. Please confirm your account.',
    'ErrorMail' => 'The mail could not be sent, please try again later.',
    'YouHaveToConfirm' => 'You must confirm the email.',
    'DeletedAccount' => "This user's account is deleted.",
    'ConfirmedMail' => 'Confirmed email. Please log in.',
    'CannotConfirm' => 'The mail could not be confirmed.',
    'UserNotFound' => 'The user does not exists',
    'InternalError' => 'An internal error has occurred.',
    'AdministrationPanel' => 'Administration panel',
    'Comments' => '',
    'Song' => '',
    'Cover' => '',
    'Home' => '',
    'Logout' => '',
];
