<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Albumes' => 'Albums',
    'Anyo' => 'Year',
    'Create Albumes' => 'Add an album',
    'Create Generos' => 'Add a genre',
    'Denominacion' => 'Denomination',
    'Generos' => 'Genres',
    'Nombre' => 'Name',
    'Titulo' => 'Title',
    'Update Albumes: {name}' => 'Update album: {name}',
    'Update Generos: {name}' => 'Update genre: {name}',
    'Usuario ID' => 'User ID',
    'Album ID' => '',
    'Apellidos' => 'Surnames',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Canciones' => 'Songs',
    'Confirm Token' => '',
    'Create Canciones' => 'Add a song',
    'Created At' => '',
    'Delete' => '',
    'Duracion' => 'Duration',
    'Email' => '',
    'Fnac' => 'Date of birth',
    'Genero ID' => 'Genre ID',
    'ID' => '',
    'Login' => '',
    'Password' => '',
    'Reset' => '',
    'Rol' => '',
    'Save' => '',
    'Search' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Canciones: {name}' => 'Update song: {name}',
    'Url Cancion' => 'Song url',
    'Url Portada' => 'Cover url',
    'Título del álbum' => 'Album title',
    'Género' => 'Genre'
];
